[package]
name = "bevy_github_ci_template"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.6"
fastrand = "1.0"
heron = { version = "2.0.1", features = ["3d"] }
ringbuffer = "0.8.2"
